layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://static.thenounproject.com/png/1870030-200.png

  - name: Blockchain
    web_url: https://github.com/topics/blockchain
    image_url: https://cdn.iconscout.com/icon/free/png-256/blockchain-2-411041.png

  - name: Quantum Computing
    image_url: http://www.stellartradingsystems.com/wp-content/uploads/2015/04/quantum.png
